services:
  app:
    build: .
    container_name: pattern-hijack
    labels:
    - "category=Injection"
    - "challenge=Pattern Hijack"
    ports:
      - 5000:5000
    environment:
      - FRONTEND_BUILD_PATH=frontend-build
    restart: always
