name: Build and Upload to S3

on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Build project
        run: |
          cd frontend
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Sync to S3 and Track Changes
        id: sync
        run: |
          CHANGED_FILES=$(aws s3 sync frontend/dist s3://samuelb.dev --delete \
            | awk '{print $NF}' | sed 's|s3://samuelb.dev||' | tr '\n' ' ')
          echo "CHANGED_FILES=${CHANGED_FILES}"
          echo "CHANGED_FILES=${CHANGED_FILES}" >> $GITHUB_ENV

      - name: Invalidate Changed Files in CloudFront
        if: env.CHANGED_FILES != ''
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths $CHANGED_FILES
